# Generated by Django 5.1.2 on 2025-10-17 17:46
# FIXED: Made ticket_no idempotent with SeparateDatabaseAndState

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0007_fix_ticket_no_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='issue',
            name='landlord_is_status_e16df2_idx',
        ),
        migrations.RemoveIndex(
            model_name='issue',
            name='landlord_is_unit_id_f9b5bb_idx',
        ),
        # FIX: Use SeparateDatabaseAndState to make ticket_no idempotent
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE landlord_issue ADD COLUMN IF NOT EXISTS ticket_no varchar(32) UNIQUE;",
                    reverse_sql="ALTER TABLE landlord_issue DROP COLUMN IF EXISTS ticket_no;",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='issue',
                    name='ticket_no',
                    field=models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='issue',
            name='severity',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In progress'), ('WAITING_TENANT', 'Waiting tenant'), ('WAITING_VENDOR', 'Waiting vendor'), ('SCHEDULED', 'Scheduled'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], db_index=True, default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='landlord.unit'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='moved_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['expires_at'], name='landlord_ch_expires_881f94_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status', '-created_at'], name='landlord_is_status_315f00_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['tenant', 'unit'], name='landlord_is_tenant__bdc42f_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['created_at'], name='landlord_is_created_562eec_idx'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.CheckConstraint(condition=models.Q(('tenant__isnull', False), ('unit__isnull', False), _connector='OR'), name='ck_issue_has_tenant_or_unit'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('moved_out_at__isnull', True)), fields=('unit',), name='uq_active_tenant_per_unit'),
        ),
    ]
