# Generated by Django 5.1.2 on 2025-10-19
# M11b: Add Document and DocumentVersion models (without FKs to Property/Unit/Tenant)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0009_merge_20251018_1855'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create Document model (without property/unit/tenant FKs - those come in 0010)
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='docs/%Y/%m/')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(
                    choices=[
                        ('vertrag', 'Vertrag'),
                        ('rechnung', 'Rechnung'),
                        ('übergabe', 'Übergabe'),
                        ('plan', 'Plan/Grundriss'),
                        ('foto', 'Foto'),
                        ('sonstiges', 'Sonstiges')
                    ],
                    default='sonstiges',
                    max_length=20
                )),
                ('related_type', models.CharField(
                    blank=True,
                    choices=[
                        ('property', 'Property'),
                        ('unit', 'Unit'),
                        ('tenant', 'Tenant'),
                        ('issue', 'Issue'),
                        ('vendor', 'Vendor')
                    ],
                    db_index=True,
                    max_length=20
                )),
                ('related_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('current_version', models.PositiveSmallIntegerField(default=1, help_text='Current version number of this document')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to=settings.AUTH_USER_MODEL
                )),
                ('supersedes', models.ForeignKey(
                    blank=True,
                    help_text='DEPRECATED: Use DocumentVersion instead',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='superseded_by',
                    to='landlord.document'
                )),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        # Add indexes to Document
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['related_type', 'related_id', 'category'], name='landlord_do_related_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='landlord_do_created_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['valid_from', 'valid_to'], name='landlord_do_valid_idx'),
        ),

        # Create DocumentVersion model
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveSmallIntegerField(help_text='Version number (1, 2, 3...)')),
                ('file', models.FileField(help_text='Archived version of the file', upload_to='docs/versions/%Y/%m/')),
                ('size_bytes', models.PositiveIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('upload_comment', models.TextField(blank=True, help_text="Comment about this version (e.g. 'Corrected rent amount')")),
                ('document', models.ForeignKey(
                    help_text='Parent document',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='versions',
                    to='landlord.document'
                )),
                ('uploaded_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='uploaded_document_versions',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        # Add unique constraint to DocumentVersion
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
        # Add indexes to DocumentVersion
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', '-version_number'], name='landlord_do_documen_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['created_at'], name='landlord_do_created_ver_idx'),
        ),
    ]
