# Generated by Django 5.1.2 on 2025-10-18 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0008_alter_issue_options_and_more'),
        ('landlord', '0002_tenantauthtoken'),
    ]

    operations = [
        # Merge migration - no operations needed
    ]
