# Generated by Django 5.1.2 on 2025-10-18 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0009_merge_20251018_1855'),
    ]

    operations = [
        # M11b: Add ForeignKeys to Document for Property/Unit/Tenant
        migrations.AddField(
            model_name='document',
            name='property',
            field=models.ForeignKey(
                blank=True,
                help_text='Dokument gehört zu diesem Objekt',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='documents',
                to='landlord.property'
            ),
        ),
        migrations.AddField(
            model_name='document',
            name='unit',
            field=models.ForeignKey(
                blank=True,
                help_text='Dokument gehört zu dieser Wohnung',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='documents',
                to='landlord.unit'
            ),
        ),
        migrations.AddField(
            model_name='document',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                help_text='Dokument gehört zu diesem Mieter',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='documents',
                to='landlord.tenant'
            ),
        ),
        # Make legacy fields nullable
        migrations.AlterField(
            model_name='document',
            name='related_type',
            field=models.CharField(blank=True, choices=[('property', 'Property'), ('unit', 'Unit'), ('tenant', 'Tenant'), ('issue', 'Issue'), ('vendor', 'Vendor')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='related_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
