# Generated by Django 5.1.2 on 2025-10-18 20:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0009_merge_20251018_1855'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='done_at',
            field=models.DateTimeField(blank=True, help_text='When status changed to RESOLVED/DONE', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='first_response_at',
            field=models.DateTimeField(blank=True, help_text='When status changed from NEW', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to='landlord.vendor'),
        ),
        migrations.AddField(
            model_name='issue',
            name='vendor_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When vendor accepted the job', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='vendor_first_contact_at',
            field=models.DateTimeField(blank=True, help_text='When vendor first logged in/commented', null=True),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='docs/%Y/%m/')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('vertrag', 'Vertrag'), ('rechnung', 'Rechnung'), ('übergabe', 'Übergabe'), ('plan', 'Plan/Grundriss'), ('foto', 'Foto'), ('sonstiges', 'Sonstiges')], default='sonstiges', max_length=20)),
                ('related_type', models.CharField(blank=True, choices=[('property', 'Property'), ('unit', 'Unit'), ('tenant', 'Tenant'), ('issue', 'Issue'), ('vendor', 'Vendor')], db_index=True, max_length=20)),
                ('related_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('current_version', models.PositiveSmallIntegerField(default=1, help_text='Current version number of this document')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('property', models.ForeignKey(blank=True, help_text='Dokument gehört zu diesem Objekt', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='landlord.property')),
                ('supersedes', models.ForeignKey(blank=True, help_text='DEPRECATED: Use DocumentVersion instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='landlord.document')),
                ('tenant', models.ForeignKey(blank=True, help_text='Dokument gehört zu diesem Mieter', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='landlord.tenant')),
                ('unit', models.ForeignKey(blank=True, help_text='Dokument gehört zu dieser Wohnung', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='landlord.unit')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(help_text='Vertragsbeginn (Einzugsdatum)')),
                ('end_date', models.DateField(blank=True, help_text='Vertragsende (leer = unbefristet)', null=True)),
                ('notice_date', models.DateField(blank=True, help_text='Kündigungsdatum (falls gekündigt)', null=True)),
                ('rent_amount', models.DecimalField(decimal_places=2, help_text='Kaltmiete pro Monat (€)', max_digits=10)),
                ('additional_costs', models.DecimalField(decimal_places=2, default=0, help_text='Nebenkosten-Vorauszahlung pro Monat (€)', max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Kaution (€)', max_digits=10)),
                ('payment_day', models.PositiveSmallIntegerField(default=3, help_text='Zahlungstag im Monat (1-28)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('active', 'Aktiv'), ('ended', 'Beendet'), ('cancelled', 'Gekündigt')], db_index=True, default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Interne Notizen zum Vertrag')),
                ('tenant', models.ForeignKey(help_text='Mieter für diesen Vertrag', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='landlord.tenant')),
                ('unit', models.ForeignKey(help_text='Wohnung für diesen Vertrag', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='landlord.unit')),
                ('document', models.ForeignKey(blank=True, help_text='Vertrags-PDF (nutzt Versionshistorie!)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='landlord.document')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='invoice_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoiced_issues', to='landlord.document'),
        ),
        migrations.AddField(
            model_name='issue',
            name='quote_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoted_issues', to='landlord.document'),
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveSmallIntegerField(help_text='Version number (1, 2, 3...)')),
                ('file', models.FileField(help_text='Archived version of the file', upload_to='docs/versions/%Y/%m/')),
                ('size_bytes', models.PositiveIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('upload_comment', models.TextField(blank=True, help_text="Comment about this version (e.g. 'Corrected rent amount')")),
                ('document', models.ForeignKey(help_text='Parent document', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='landlord.document')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_document_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='VendorAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('estimate', 'Kostenvoranschlag'), ('invoice', 'Rechnung'), ('other', 'Sonstiges')], max_length=20)),
                ('file', models.FileField(upload_to='vendor/%Y/%m/%d/')),
                ('mime', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the file')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_attachments', to='landlord.issue')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='landlord.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VendorAuthToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('invite', 'Invitation')], default='login', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('ua_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='landlord.vendor')),
            ],
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['related_type', 'related_id', 'category'], name='landlord_do_related_976c99_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='landlord_do_created_7890e7_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['valid_from', 'valid_to'], name='landlord_do_valid_f_ce0df8_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['unit', 'status'], name='landlord_co_unit_id_acbb91_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tenant', 'status'], name='landlord_co_tenant__b38945_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['start_date', 'end_date'], name='landlord_co_start_d_5aca3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('unit',), name='unique_active_contract_per_unit'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', '-version_number'], name='landlord_do_documen_687843_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['created_at'], name='landlord_do_created_b25c0e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='vendorauthtoken',
            index=models.Index(fields=['vendor', 'purpose', 'expires_at'], name='vendor_auth_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorauthtoken',
            index=models.Index(fields=['email', 'expires_at'], name='vendor_email_expires_idx'),
        ),
    ]
