# Generated by Django 5.1.2 on 2025-10-19
# M12a: Add Contract and PaymentTransaction models (Document already exists from 0009b/0010)

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0010_document_fk_relations_m11b'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add Issue fields for vendor tracking (M10)
        migrations.AddField(
            model_name='issue',
            name='done_at',
            field=models.DateTimeField(blank=True, help_text='When status changed to RESOLVED/DONE', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='first_response_at',
            field=models.DateTimeField(blank=True, help_text='When status changed from NEW', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to='landlord.vendor'),
        ),
        migrations.AddField(
            model_name='issue',
            name='vendor_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When vendor accepted the job', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='vendor_first_contact_at',
            field=models.DateTimeField(blank=True, help_text='When vendor first logged in/commented', null=True),
        ),

        # Add Document FKs to Issue for quotes/invoices (M10/M11b)
        migrations.AddField(
            model_name='issue',
            name='quote_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoted_issues', to='landlord.document'),
        ),
        migrations.AddField(
            model_name='issue',
            name='invoice_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoiced_issues', to='landlord.document'),
        ),

        # M12a: Create Contract model
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(help_text='Vertragsbeginn (Einzugsdatum)')),
                ('end_date', models.DateField(blank=True, help_text='Vertragsende (leer = unbefristet)', null=True)),
                ('notice_date', models.DateField(blank=True, help_text='Kündigungsdatum (falls gekündigt)', null=True)),
                ('rent_amount', models.DecimalField(decimal_places=2, help_text='Kaltmiete pro Monat (€)', max_digits=10)),
                ('additional_costs', models.DecimalField(decimal_places=2, default=0, help_text='Nebenkosten-Vorauszahlung pro Monat (€)', max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Kaution (€)', max_digits=10)),
                ('payment_day', models.PositiveSmallIntegerField(default=3, help_text='Zahlungstag im Monat (1-28)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('active', 'Aktiv'), ('ended', 'Beendet'), ('cancelled', 'Gekündigt')], db_index=True, default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Interne Notizen zum Vertrag')),
                ('tenant', models.ForeignKey(help_text='Mieter für diesen Vertrag', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='landlord.tenant')),
                ('unit', models.ForeignKey(help_text='Wohnung für diesen Vertrag', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='landlord.unit')),
                ('document', models.ForeignKey(blank=True, help_text='Vertrags-PDF (nutzt Versionshistorie!)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='landlord.document')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),

        # M12b: Create PaymentTransaction model
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Betrag in Euro', max_digits=10)),
                ('transaction_date', models.DateField(help_text='Buchungsdatum')),
                ('payment_type', models.CharField(
                    choices=[('rent', 'Miete'), ('deposit', 'Kaution'), ('utilities', 'Nebenkosten'), ('other', 'Sonstiges')],
                    default='rent',
                    max_length=20
                )),
                ('status', models.CharField(
                    choices=[('pending', 'Ausstehend'), ('received', 'Eingegangen'), ('returned', 'Rückerstattet'), ('cancelled', 'Storniert')],
                    default='pending',
                    max_length=20
                )),
                ('reference', models.CharField(blank=True, help_text='Verwendungszweck/Buchungstext', max_length=500)),
                ('sender_name', models.CharField(blank=True, help_text='Auftraggeber/Sender', max_length=200)),
                ('sender_iban', models.CharField(blank=True, help_text='IBAN des Senders', max_length=34)),
                ('notes', models.TextField(blank=True)),
                ('csv_import_date', models.DateTimeField(blank=True, help_text='Wann wurde dieser Eintrag via CSV importiert?', null=True)),
                ('csv_row_data', models.JSONField(blank=True, default=dict, help_text='Rohdaten aus CSV-Import für Debugging')),
                ('contract', models.ForeignKey(help_text='Zugehöriger Mietvertrag', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='landlord.contract')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),

        # Add indexes
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['contract', 'transaction_date'], name='landlord_pa_contrac_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_date'], name='landlord_pa_transac_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status'], name='landlord_pa_status_idx'),
        ),

        # Add contract indexes
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['unit', 'status'], name='landlord_co_unit_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tenant'], name='landlord_co_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['start_date'], name='landlord_co_start_idx'),
        ),
    ]
