# Generated by Django 5.1.2 on 2025-10-19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0010_document_fk_relations_m11b'),
        ('landlord', '0011_add_contract_model_m12a'),
    ]

    operations = [
        # Merge migration - no operations needed
    ]
