# Generated by Django 5.1.2 on 2025-10-19
# M14: Add UtilityReading model for utility cost calculations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0012_merge_20251019'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meter_type', models.CharField(
                    choices=[
                        ('water_cold', 'Kaltwasser'),
                        ('water_hot', 'Warmwasser'),
                        ('electricity', 'Strom'),
                        ('gas', 'Gas'),
                        ('heating', 'Heizung')
                    ],
                    help_text='Art des Zählers',
                    max_length=20
                )),
                ('reading_date', models.DateField(help_text='Datum der Ablesung')),
                ('meter_number', models.CharField(blank=True, help_text='Zählernummer (optional)', max_length=50)),
                ('current_value', models.DecimalField(decimal_places=2, help_text='Aktueller Zählerstand', max_digits=10)),
                ('previous_value', models.DecimalField(
                    blank=True,
                    decimal_places=2,
                    help_text='Vorheriger Zählerstand (optional, wird automatisch gesetzt)',
                    max_digits=10,
                    null=True
                )),
                ('consumption', models.DecimalField(
                    blank=True,
                    decimal_places=2,
                    help_text='Verbrauch (current - previous, wird automatisch berechnet)',
                    max_digits=10,
                    null=True
                )),
                ('notes', models.TextField(blank=True, help_text='Notizen zur Ablesung')),
                ('unit', models.ForeignKey(
                    help_text='Wohnung für die der Zählerstand erfasst wird',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='utility_readings',
                    to='landlord.unit'
                )),
                ('recorded_by', models.ForeignKey(
                    blank=True,
                    help_text='Wer hat den Zählerstand erfasst?',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='utility_readings',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'ordering': ['-reading_date', '-created_at'],
            },
        ),
        # Add indexes
        migrations.AddIndex(
            model_name='utilityreading',
            index=models.Index(fields=['unit', 'meter_type', 'reading_date'], name='landlord_ut_unit_meter_date_idx'),
        ),
        migrations.AddIndex(
            model_name='utilityreading',
            index=models.Index(fields=['reading_date'], name='landlord_ut_reading_date_idx'),
        ),
        # Add unique constraint
        migrations.AddConstraint(
            model_name='utilityreading',
            constraint=models.UniqueConstraint(
                fields=['unit', 'meter_type', 'reading_date'],
                name='unique_reading_per_unit_type_date'
            ),
        ),
    ]
