# Generated by Django 5.1.2 on 2025-10-19
# M14: Add allocation_key field to Contract for utility cost distribution

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0012b_add_utilityreading_m14'),
    ]

    operations = [
        # Add allocation_key field to Contract for M14 (Utility Billing)
        migrations.AddField(
            model_name='contract',
            name='allocation_key',
            field=models.CharField(
                choices=[
                    ('area', 'Wohnfläche (qm)'),
                    ('persons', 'Personenanzahl'),
                    ('units', 'Anzahl Einheiten'),
                    ('consumption', 'Verbrauch'),
                ],
                default='area',
                help_text='Umlageschlüssel für Nebenkostenabrechnung',
                max_length=20
            ),
        ),
    ]
