# Generated by Django 5.1.2 on 2025-10-19
# Placeholder migration for M14 (Utility Calculations)
# This migration is needed to fix the migration chain but M14 is not yet fully implemented

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0012b_add_utilityreading_m14'),
    ]

    operations = [
        # Placeholder - M14 (Utility Calculations) not yet implemented
        # This migration exists only to maintain the migration chain
    ]
