# Generated by Django 5.1.2 on 2025-10-19 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0013_add_allocation_keys_to_contract_m14'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name der Vorlage (z.B. "Standard Einzugsprotokoll")', max_length=200)),
                ('template_type', models.CharField(choices=[('move_in', 'Einzugsprotokoll'), ('move_out', 'Auszugsprotokoll'), ('inspection', 'Wohnungsbesichtigung'), ('maintenance', 'Wartungsprotokoll'), ('custom', 'Benutzerdefiniert')], help_text='Art der Checkliste', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Beschreibung und Verwendungszweck')),
                ('is_active', models.BooleanField(default=True, help_text='Ist diese Vorlage aktiv?')),
                ('default_items', models.JSONField(default=list, help_text='Standard-Prüfpunkte als JSON Array: [{"name": "...", "category": "...", "order": 1}]')),
            ],
            options={
                'ordering': ['template_type', 'name'],
                'indexes': [models.Index(fields=['template_type', 'is_active'], name='landlord_ch_templat_3eb2a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Titel der Checkliste', max_length=200)),
                ('checklist_type', models.CharField(choices=[('move_in', 'Einzugsprotokoll'), ('move_out', 'Auszugsprotokoll'), ('inspection', 'Wohnungsbesichtigung'), ('maintenance', 'Wartungsprotokoll'), ('custom', 'Benutzerdefiniert')], help_text='Art der Checkliste', max_length=20)),
                ('checklist_date', models.DateField(help_text='Datum der Begehung/Prüfung')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('in_progress', 'In Bearbeitung'), ('completed', 'Abgeschlossen'), ('archived', 'Archiviert')], default='draft', max_length=20)),
                ('general_notes', models.TextField(blank=True, help_text='Allgemeine Anmerkungen')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Wann wurde die Checkliste abgeschlossen?', null=True)),
                ('conducted_by', models.ForeignKey(blank=True, help_text='Durchgeführt von (Staff)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_checklists', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Mieter (bei Ein-/Auszug)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='landlord.tenant')),
                ('unit', models.ForeignKey(help_text='Wohnung für die diese Checkliste gilt', on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='landlord.unit')),
                ('template', models.ForeignKey(blank=True, help_text='Vorlage (optional, falls aus Template erstellt)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='landlord.checklisttemplate')),
            ],
            options={
                'ordering': ['-checklist_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(help_text='Kategorie (z.B. "Küche", "Bad", "Wohnzimmer")', max_length=100)),
                ('name', models.CharField(help_text='Name des Prüfpunkts (z.B. "Herd", "Dusche", "Fenster")', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Reihenfolge der Anzeige')),
                ('is_checked', models.BooleanField(default=False, help_text='Wurde dieser Punkt geprüft?')),
                ('condition', models.CharField(blank=True, choices=[('excellent', 'Sehr gut'), ('good', 'Gut'), ('fair', 'Befriedigend'), ('poor', 'Schlecht'), ('damaged', 'Beschädigt'), ('n/a', 'Nicht zutreffend')], help_text='Zustand des geprüften Elements', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Anmerkungen zu diesem Prüfpunkt')),
                ('photo', models.ImageField(blank=True, help_text='Beweisfoto (optional)', null=True, upload_to='checklists/%Y/%m/')),
                ('checklist', models.ForeignKey(help_text='Zugehörige Checkliste', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='landlord.checklist')),
            ],
            options={
                'ordering': ['checklist', 'order', 'category', 'name'],
                'indexes': [models.Index(fields=['checklist', 'order'], name='landlord_ch_checkli_f3ffca_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='checklist',
            index=models.Index(fields=['unit', 'checklist_date'], name='landlord_ch_unit_id_52421e_idx'),
        ),
        migrations.AddIndex(
            model_name='checklist',
            index=models.Index(fields=['status', 'checklist_date'], name='landlord_ch_status_4ff9eb_idx'),
        ),
    ]
