# Generated by Django 5.1.2 on 2025-10-19 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0014_add_checklist_models_m16'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('smoke_detector', 'Rauchmelder'), ('heating', 'Heizung'), ('elevator', 'Aufzug'), ('fire_extinguisher', 'Feuerlöscher'), ('inspection', 'Begehung'), ('other', 'Sonstiges')], max_length=30)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('completed', 'Erledigt'), ('cancelled', 'Abgebrochen')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_maintenance', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_items', to='landlord.property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_items', to='landlord.unit')),
            ],
            options={
                'ordering': ['due_date', 'category'],
                'indexes': [models.Index(fields=['status', 'due_date'], name='landlord_ma_status_98f526_idx'), models.Index(fields=['property', 'due_date'], name='landlord_ma_propert_18fb36_idx')],
            },
        ),
    ]
