# Generated by Django 5.1.13 on 2025-10-19 07:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0015_add_maintenance_models_m15'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('estimate', 'Kostenvoranschlag'), ('invoice', 'Rechnung'), ('other', 'Sonstiges')], max_length=20)),
                ('file', models.FileField(upload_to='vendor/%Y/%m/%d/')),
                ('mime', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VendorAuthToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('invite', 'Invitation')], default='login', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('ua_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='contract',
            name='landlord_co_tenant_idx',
        ),
        migrations.RemoveIndex(
            model_name='contract',
            name='landlord_co_start_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='landlord_pa_transac_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='landlord_pa_status_idx',
        ),
        migrations.RenameIndex(
            model_name='contract',
            new_name='landlord_co_unit_id_acbb91_idx',
            old_name='landlord_co_unit_status_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='landlord_do_related_976c99_idx',
            old_name='landlord_do_related_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='landlord_do_created_7890e7_idx',
            old_name='landlord_do_created_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='landlord_do_valid_f_ce0df8_idx',
            old_name='landlord_do_valid_idx',
        ),
        migrations.RenameIndex(
            model_name='documentversion',
            new_name='landlord_do_documen_687843_idx',
            old_name='landlord_do_documen_idx',
        ),
        migrations.RenameIndex(
            model_name='documentversion',
            new_name='landlord_do_created_b25c0e_idx',
            old_name='landlord_do_created_ver_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='landlord_pa_contrac_5816f9_idx',
            old_name='landlord_pa_contrac_idx',
        ),
        migrations.RenameIndex(
            model_name='utilityreading',
            new_name='landlord_ut_unit_id_aae9a6_idx',
            old_name='landlord_ut_unit_meter_date_idx',
        ),
        migrations.RenameIndex(
            model_name='utilityreading',
            new_name='landlord_ut_reading_34565c_idx',
            old_name='landlord_ut_reading_date_idx',
        ),
        migrations.AddField(
            model_name='contract',
            name='occupants_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Anzahl der Bewohner (für Personen-Umlage, M14)', null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='due_date',
            field=models.DateField(blank=True, help_text='Fälligkeitsdatum (wenn bekannt)', null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='allocation_key',
            field=models.CharField(choices=[('area', 'Nach Fläche (m²)'), ('persons', 'Nach Personenzahl'), ('consumption', 'Nach Verbrauch'), ('units', 'Nach Anzahl Wohnungen (gleichmäßig)')], default='area', help_text='Wie werden Nebenkosten umgelegt? (M14)', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Betrag in €', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='csv_import_date',
            field=models.DateTimeField(blank=True, help_text='Wann wurde diese Zahlung importiert?', null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='csv_row_data',
            field=models.JSONField(blank=True, help_text='Original CSV-Zeile für Debugging', null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='notes',
            field=models.TextField(blank=True, help_text='Interne Notizen'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_type',
            field=models.CharField(choices=[('rent', 'Miete'), ('deposit', 'Kaution'), ('additional_costs', 'Nebenkosten'), ('other', 'Sonstiges')], db_index=True, default='rent', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='reference',
            field=models.CharField(blank=True, help_text='Verwendungszweck / Referenz', max_length=500),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='sender_iban',
            field=models.CharField(blank=True, help_text='IBAN des Zahlenden', max_length=34),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='sender_name',
            field=models.CharField(blank=True, help_text='Name des Zahlenden', max_length=200),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('received', 'Eingegangen'), ('overdue', 'Überfällig'), ('cancelled', 'Storniert')], db_index=True, default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_date',
            field=models.DateField(help_text='Datum der Transaktion (Valutadatum)'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tenant', 'status'], name='landlord_co_tenant__b38945_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['start_date', 'end_date'], name='landlord_co_start_d_5aca3b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_date', 'status'], name='landlord_pa_transac_12b650_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment_type', 'status'], name='landlord_pa_payment_032ccc_idx'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('unit',), name='unique_active_contract_per_unit'),
        ),
        migrations.AddField(
            model_name='vendorattachment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_attachments', to='landlord.issue'),
        ),
        migrations.AddField(
            model_name='vendorattachment',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='landlord.vendor'),
        ),
        migrations.AddField(
            model_name='vendorauthtoken',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='landlord.vendor'),
        ),
        migrations.AddIndex(
            model_name='vendorauthtoken',
            index=models.Index(fields=['vendor', 'purpose', 'expires_at'], name='vendor_auth_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorauthtoken',
            index=models.Index(fields=['email', 'expires_at'], name='vendor_email_expires_idx'),
        ),
    ]
