# Generated by Django 5.1.13 on 2025-10-20 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0016_vendorattachment_vendorauthtoken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_type', models.CharField(choices=[('property', 'Gebäudezähler'), ('unit', 'Wohnungszähler')], help_text='Ist dies ein Gebäude- oder Wohnungszähler?', max_length=10)),
                ('meter_type', models.CharField(choices=[('cold_water', 'Kaltwasser'), ('hot_water', 'Warmwasser'), ('electricity', 'Strom'), ('gas', 'Gas (kWh)')], help_text='Art des Zählers (Medium)', max_length=20)),
                ('serial_number', models.CharField(blank=True, help_text='Seriennummer des Versorgers (optional)', max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='Standardzähler für automatisches Vorbefüllen (max. 1 pro Scope+Medium)')),
                ('is_active', models.BooleanField(default=True, help_text='Ist der Zähler aktiv/installiert?')),
                ('initial_reading_value', models.DecimalField(blank=True, decimal_places=2, help_text='Startwert bei Installation (wird einmalig als "vorheriger Stand" verwendet)', max_digits=10, null=True)),
                ('installed_at', models.DateField(blank=True, help_text='Installationsdatum', null=True)),
                ('removed_at', models.DateField(blank=True, help_text='Datum der Entfernung/Deaktivierung', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notizen zum Zähler')),
                ('property', models.ForeignKey(blank=True, help_text='Gebäude (nur wenn Gebäudezähler)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utility_meters', to='landlord.property')),
                ('unit', models.ForeignKey(blank=True, help_text='Wohnung (nur wenn Wohnungszähler)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utility_meters', to='landlord.unit')),
            ],
            options={
                'ordering': ['scope_type', 'meter_type', '-is_default', '-is_active', 'serial_number'],
                'indexes': [models.Index(fields=['scope_type', 'property', 'meter_type'], name='landlord_ut_scope_t_ab7581_idx'), models.Index(fields=['scope_type', 'unit', 'meter_type'], name='landlord_ut_scope_t_b73331_idx'), models.Index(fields=['is_default', 'is_active'], name='landlord_ut_is_defa_f0a7a8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True), ('scope_type', 'property')), fields=('scope_type', 'property', 'meter_type'), name='unique_default_meter_property'), models.UniqueConstraint(condition=models.Q(('is_default', True), ('scope_type', 'unit')), fields=('scope_type', 'unit', 'meter_type'), name='unique_default_meter_unit'), models.CheckConstraint(condition=models.Q(models.Q(('property__isnull', False), ('scope_type', 'property'), ('unit__isnull', True)), models.Q(('property__isnull', True), ('scope_type', 'unit'), ('unit__isnull', False)), _connector='OR'), name='utility_meter_scope_consistency')],
            },
        ),
    ]
