# Generated by Django 5.1.13 on 2025-10-20 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0017_add_utility_meter_m17'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when property was archived', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='archived_by',
            field=models.ForeignKey(blank=True, help_text='User who archived this property', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag for archived properties'),
        ),
    ]
