# Generated by Django 5.1.13 on 2025-10-20 21:42

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0018_add_property_archive_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='geo_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude (-90.0 to +90.0)', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='geo_lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude (-180.0 to +180.0)', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('geo_lat__isnull', True), models.Q(('geo_lat__gte', -90.0), ('geo_lat__lte', 90.0)), _connector='OR'), name='property_geo_lat_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('geo_lng__isnull', True), models.Q(('geo_lng__gte', -180.0), ('geo_lng__lte', 180.0)), _connector='OR'), name='property_geo_lng_valid_range'),
        ),
    ]
