# Generated by Django 5.1.13 on 2025-10-20 22:10

# Generated by Django 5.1.13 on 2025-10-20 22:08

from django.db import migrations


def migrate_country_names_to_codes(apps, schema_editor):
    """
    Migrate existing country names to country codes BEFORE changing field size:
    - Deutschland → DE
    - Österreich → AT  
    - Schweiz → CH
    """
    Property = apps.get_model('landlord', 'Property')
    
    # Mapping of old names to new codes
    country_mapping = {
        'Deutschland': 'DE',
        'Germany': 'DE',
        'Österreich': 'AT',
        'Austria': 'AT',
        'Schweiz': 'CH',
        'Switzerland': 'CH',
    }
    
    for old_name, new_code in country_mapping.items():
        Property.objects.filter(country=old_name).update(country=new_code)
    
    # Any remaining countries default to DE
    valid_codes = ['DE', 'AT', 'CH']
    Property.objects.exclude(country__in=valid_codes).update(country='DE')


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0019_add_geo_coordinate_constraints'),
    ]

    operations = [
        migrations.RunPython(migrate_country_names_to_codes, reverse_code=migrations.RunPython.noop),
    ]
