# Generated by Django 5.1.13 on 2025-10-20 22:13

import landlord.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0020_migrate_country_names_to_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(choices=[('DE', 'Deutschland'), ('AT', 'Österreich'), ('CH', 'Schweiz')], default='DE', help_text='Country code (DE, AT, CH)', max_length=2, validators=[landlord.validators.validate_country_whitelist]),
        ),
    ]
