# Generated by Django 5.1.13 on 2025-10-20 22:44

import landlord.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0021_update_country_field_with_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilitymeter',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Seriennummer des Versorgers (optional, A-Z/a-z/0-9/-/)', max_length=50, validators=[landlord.validators.validate_serial_number_format]),
        ),
    ]
