# Generated by Django 5.1.13 on 2025-10-20 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0022_update_utility_meter_serial_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['name'], name='landlord_pr_name_62278f_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city'], name='landlord_pr_city_8c4603_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['postal_code'], name='landlord_pr_postal__cc7234_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_archived'], name='landlord_pr_is_arch_a51b53_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'postal_code'], name='landlord_pr_city_c143a9_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['-created_at'], name='landlord_pr_created_83876f_idx'),
        ),
    ]
