# Generated by Django 5.1.13 on 2025-10-21 06:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0023_add_property_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when unit was archived', null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='archived_by',
            field=models.ForeignKey(blank=True, help_text='User who archived this unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag for archived units'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Area in square meters (must be >= 0)', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['is_archived'], name='landlord_un_is_arch_91e776_idx'),
        ),
    ]
