# Generated by Django 5.1.13 on 2025-10-23 12:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('landlord', '0024_unit_archive_fields_phase1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(help_text='Email stored for reference even if user is deleted', max_length=255)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('archive', 'Archive'), ('unarchive', 'Unarchive'), ('gdpr_erase', 'GDPR Data Erasure'), ('export', 'Data Export'), ('permission_change', 'Permission Change')], db_index=True, help_text='Type of action performed', max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('resource_repr', models.CharField(help_text='String representation of resource at time of action', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional structured data about the action')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the action occurred')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from request')),
                ('request_id', models.CharField(blank=True, help_text='Request ID for correlation with application logs', max_length=36)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='landlord_au_timesta_cbe451_idx'), models.Index(fields=['action', '-timestamp'], name='landlord_au_action_de432b_idx'), models.Index(fields=['user', '-timestamp'], name='landlord_au_user_id_e9499e_idx'), models.Index(fields=['content_type', 'object_id'], name='landlord_au_content_eb7689_idx')],
            },
        ),
    ]
