# Generated by Django 5.1.13 on 2025-10-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0025_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Mieter', 'verbose_name_plural': 'Mieter'},
        ),
        migrations.AddField(
            model_name='tenant',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Optional - für SCHUFA, Altersverifikation', null=True, verbose_name='Geburtsdatum'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='Kontaktperson im Notfall', max_length=200, verbose_name='Notfallkontakt Name'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Notfallkontakt Telefon'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='first_name',
            field=models.CharField(blank=True, default='', help_text='Vorname des Mieters (§ 550 BGB erforderlich)', max_length=100, verbose_name='Vorname'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='last_name',
            field=models.CharField(blank=True, default='', help_text='Nachname des Mieters (§ 550 BGB erforderlich)', max_length=100, verbose_name='Nachname'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='notes',
            field=models.TextField(blank=True, help_text='Interne Notizen (nicht für Mieter sichtbar)', verbose_name='Notizen'),
        ),
    ]
